import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import MiddleBox from "@/components/middleBox";
import MiddleBoxGrid from "@/components/middle-box-grid";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container__red">
          <MiddleBox />
        </div>
        <div className="container__blue">
          <MiddleBoxGrid />
        </div>
      </main>
    </>
  );
}
